models:
  container_model: "./models/mahindra_and_mahindra_pallet_model.pt"
  pallet_status_model: "./models/new pallet status model.pt"
  box_model: "./models/Marico Box Detection.pt"
  boundary_model: "./models/new_blue_orange_bar.pt"

bars:
  vertical: 0
  horizontal: 1

rack_infer_func:
  path: "package/infer functions/m&m_infer_func.py"

# pattern:
#   rack_id: '^[A-Z]{2}[-\s]?[0-9]{3}$'

rack_id:
  pattern: '^[A-O](?:[1-9]|1[0-1])-R(?:[1-8])-[AB]$'
  expected_length: 8

input:
  image_dir: "./testing images/images/m&m"
  stack_levels_csv: "./inventory data/marico_inventory_stack_levels.csv"

thresholds:
  boundary_model:
    confidence_threshold: 0.5
    merge_threshold: 50

  box_model:
    confidence_threshold: 0.2
  
  ocr_threshold:
    area_threshold: 10000
  
  container_model:
    confidence_threshold: 0.5
    distance_threshold: 200

unique_id:
  area: 250


nomenclature: 'pallets'
