models:
  qr_model: "./models/qr_detection.pt"
  container_model: "./models/mahindra_box_best.pt"
  boundary_model: "./models/Mahindra_orange_blue.pt"

bars:
  vertical: 1
  horizontal: 0

rack_infer_func:
  path: "package/infer functions/mahindra_infer_func.py"

input:
  image_dir: "./testing images/images/mahindra"

# pattern:
#   rack_id: "^HD-(\\d{2})/([A-Z])/((0[1-9])|(1[0-9])|(2[0-9])|(3[0-8]))$"

rack_id:
  pattern: "^HD-(\\d{2})/([A-Z])/((0[1-9])|(1[0-9])|(2[0-9])|(3[0-8]))$"
  expected_length: 10

thresholds:
  boundary_model:
    confidence_threshold: 0.2
    merge_threshold: 50

  box_model:
    confidence_threshold: 0.2
  
  ocr_threshold:
    area_threshold: 5000

unique_id:
  area: 750

nomenclature: 'boxes'
